name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: g++
        run: |
             g++ --version
             g++ main.cpp -I include -std=c++20 -O2 -Wall -Wextra -pedantic -Wshadow -Wunused -Wconversion -Werror
             ./a.out
  
      - name: clang++
        run: |
             clang++ --version
             clang++ main.cpp -I include -std=c++20 -O2 -Wall -Wextra -pedantic -Wshadow -Wunused -Wconversion -Werror
             ./a.out

  static_analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: clang-tidy
        run: |
             clang-tidy --version
             clang-tidy include/safe_env/*.hpp main.cpp --checks="*,-llvmlibc-*,-modernize-use-trailing-return-type,-fuchsia-default-arguments-calls,-altera-unroll-loops" --warnings-as-errors="*" -- -I include -std=c++20

  documentation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: doxygen
        run: |
             sudo apt-get install -y doxygen
             doxygen --version
             doxygen .doxygen
